name: Feature request
description: Suggest an idea for Concorde EFB
title: "[Feature]: "
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Concorde EFB! Please fill this out as clearly as possible.

  - type: input
    id: version
    attributes:
      label: App version
      description: What version are you on? (e.g., v0.85)
      placeholder: v0.85
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Web (GitHub Pages)
        - PWA (Installed)
        - Windows
        - Android
        - iOS
        - Other
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: What do you want added/changed?
      description: Explain the feature as if you're briefing a developer.
      placeholder: I want a button that...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      placeholder: This helps because...
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Extra details / references
      description: Manual page refs, screenshots, links, numbers, etc.
      placeholder: DC Designs manual page..., screenshot link..., etc.
    validations:
      required: false